version: '3.0'

expectations:
  population_size: 1000

actions:


# Asthma register (ast_reg) Dictionary method actions
  generate_study_population_ast_reg:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_ast_reg 
      --index-date-range "2019-03-01 to 2022-03-31 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_ast_reg*.csv
  
  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv

  join_ethnicity_ast_reg:
    run: >
      cohort-joiner:v0.0.12 
        --lhs output/input_ast*.csv
        --rhs output/input_ethnicity*.csv
        --output-dir output/joined
    needs: [generate_study_population_ethnicity, generate_study_population_ast_reg]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_ast*.csv

  generate_measures_ast_reg:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_ast_reg 
       --output-dir=output/joined
     needs: [join_ethnicity_ast_reg]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_ast_reg_*_rate.csv
  
  calculate_rates_ast_reg:
      run: python:latest python analysis/rate_calculations.py
      needs: [generate_measures_ast_reg]
      outputs:
        moderately_sensitive:
          tables: output/rate_table_*.csv
          plots: output/plot_*.png
          decile_chart: output/decile_chart.png

  # generate_notebook:
  #   run: jupyter:latest jupyter nbconvert /workspace/analysis/qof_notebook.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
  #   needs: [calculate_rates_ast_reg]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/qof_notebook.html