version: '3.0'

expectations:
  population_size: 1000

actions:

##########################################################
# Asthma register (ast_reg) Dictionary method actions
##########################################################
  generate_study_population_ast_reg:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_ast_reg 
      --index-date-range "2019-03-01 to 2023-09-30 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_ast_reg*.csv
  
  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv

  join_ethnicity_ast_reg:
    run: >
      cohort-joiner:'v0.0.56'
        --lhs output/input_ast*.csv
        --rhs output/input_ethnicity.csv
        --output-dir output/joined
    needs: [generate_study_population_ethnicity, generate_study_population_ast_reg]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_ast*.csv

  generate_measures_ast_reg:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_ast_reg 
       --output-dir=output/joined
     needs: [join_ethnicity_ast_reg]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_ast_reg_*_rate.csv

  calculate_rates_ast_reg:
      run: python:latest python analysis/rate_calculations_ast_reg.py
      needs: [generate_measures_ast_reg]
      outputs:
        moderately_sensitive:
          tables: output/rate_table_ast_reg_*.csv
          plots: output/plot_ast_reg_*.png
          decile_chart: output/decile_chart.png

  join_measures_register:
      run: python:latest python analysis/join_and_round.py
           --input-list output/joined/measure_ast_reg_total_rate.csv
           --input-list output/joined/measure_ast_reg_age_band_rate.csv
           --input-list output/joined/measure_ast_reg_care_home_rate.csv
           --input-list output/joined/measure_ast_reg_ethnicity_rate.csv
           --input-list output/joined/measure_ast_reg_imd_rate.csv
           --input-list output/joined/measure_ast_reg_learning_disability_rate.csv
           --input-list output/joined/measure_ast_reg_region_rate.csv
           --input-list output/joined/measure_ast_reg_sex_rate.csv
           --output-dir output/joined/summary
           --output-name "measure_register.csv"
      needs: [generate_measures_ast_reg]
      outputs:
        moderately_sensitive:
          # Only output the single summary file
          measure_csv: output/joined/summary/measure_register.csv  
##########################################################
 # Asthma indicator (ast007) Dictionary method actions
##########################################################
  generate_study_population_ast007:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_ast007 
      --index-date-range "2019-03-01 to 2023-09-30 by month" 
      --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/input_ast007*.csv

  join_ethnicity_ast007:
    run: >
      cohort-joiner:'v0.0.56'
        --lhs output/input_ast007*.csv
        --rhs output/input_ethnicity.csv
        --output-dir output/joined
    needs: [generate_study_population_ethnicity, generate_study_population_ast007]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_ast007*.csv

  generate_measures_ast007:
      run: cohortextractor:latest generate_measures 
        --study-definition study_definition_ast007 
        --output-dir=output/joined
      needs: [generate_study_population_ast007, generate_study_population_ethnicity, join_ethnicity_ast007]
      outputs:
        moderately_sensitive:
          measure_csv: output/joined/measure_*_rate.csv

  join_measures_ast007:
      run: python:latest python analysis/join_and_round.py
           --input-list output/joined/measure_ast007_total_rate.csv
           --input-list output/joined/measure_ast007_age_band_rate.csv
           --input-list output/joined/measure_ast007_care_home_rate.csv
           --input-list output/joined/measure_ast007_ethnicity_rate.csv
           --input-list output/joined/measure_ast007_imd_rate.csv
           --input-list output/joined/measure_ast007_learning_disability_rate.csv
           --input-list output/joined/measure_ast007_region_rate.csv
           --input-list output/joined/measure_ast007_sex_rate.csv
           --output-dir output/joined/summary
           --output-name "measure_ast007.csv"
      needs: [generate_measures_ast007]
      outputs:
        moderately_sensitive:
          # Only output the single summary file
          measure_csv: output/joined/summary/measure_ast007.csv  

 #############################
  # Plotting 
  #############################
  generate_astreg_deciles_charts:
    run: >
            deciles-charts:v0.0.15
            --input-files output/joined/measure_ast_reg_*_practice_rate.csv
            --output-dir output/joined
    config:
      show_outer_percentiles: false
      tables:
        output: true
      charts:
        output: true
    needs: [generate_measures_ast_reg]
    outputs:
      moderately_sensitive:
        deciles_charts: output/joined/deciles_ast_reg_*.png 
        deciles_tables: output/joined/deciles_ast_reg_*.csv  

  generate_ast007_deciles_charts:
    run: >
            deciles-charts:v0.0.15
            --input-files output/joined/measure_ast007_*_practice_rate.csv
            --output-dir output/joined
    config:
      show_outer_percentiles: false
      tables:
        output: true
      charts:
        output: true
    needs: [generate_measures_ast007]
    outputs:
      moderately_sensitive:
        deciles_charts: output/joined/deciles_ast007_*.png 
        deciles_tables: output/joined/deciles_ast007_*.csv          

  generate_qof_groups:
    run: >
            python:latest python analysis/group_charts.py
            --input-files output/joined/measure_ast_reg_*.csv
            --output-dir output/joined
            --date-lines "2019-03-31" "2020-03-31" "2021-03-31" "2022-03-31" "2023-03-31"
            --scale "percentage"
    needs: [generate_measures_ast_reg]
    outputs:
      moderately_sensitive:
        cohort: output/joined/group_chart_*.png

  generate_all_breakdowns:
    run: >
            python:latest python analysis/panel_plots.py
            --input-file output/joined/summary/measure_register.csv
            --measures-pattern "*_rate"
            --output-dir output/joined/summary
            --output-name "asthma_register_by_demographic_group"
            --date-lines "2019-03-31" "2020-03-31" "2021-03-31" "2022-03-31" "2023-03-31"
            --scale "percentage"
    needs: [generate_measures_ast_reg,join_measures_register]
    outputs:
      moderately_sensitive:
        cohort: output/joined/summary/asthma_register_by_demographic_group.png

  generate_table1:
    run: r:latest analysis/table1.r
    needs: [join_measures_register]
    outputs:
      moderately_sensitive:
        table: output/joined/summary/tab1_ast005_fy2223.html